benchmark: false
bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
dataset:
  cache_load: false
  cache_save: false
  dir: datasets
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: true
  edge_encoder_name: Bond
  edge_encoder_num_types: 0
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: true
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: OGB
  label_column: none
  label_table: none
  location: local
  name: peptides-functional
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Atom
  node_encoder_num_types: 0
  regression_targets: []
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  shuffle_split: true
  slic_compactness: 10
  split:
  - 0.8
  - 0.1
  - 0.1
  split_dir: ./splits
  split_index: 0
  split_mode: standard
  task: graph
  task_type: classification_multilabel
  to_undirected: false
  transductive: false
  transform: none
  tu_simple: true
device: cuda
edge_dim: 0
edge_types: []
example_arg: example
example_group:
  example_arg: example
# gnn:
#   act: relu
#   agg: mean
#   att_final_linear: false
#   att_final_linear_bn: false
#   att_heads: 1
#   batchnorm: true
#   clear_feature: true
#   dim_inner: 42
#   dropout: 0.0
#   head: graph
#   keep_edge: 0.5
#   l2norm: true
#   layer_type: drew_gcnconv
#   layers_mp: 23
#   layers_post_mp: 1
#   layers_pre_mp: 0
#   msg_direction: single
#   normalize_adj: false
#   residual: false
#   self_msg: concat
#   skip_every: 1
#   stage_type: frond_gnn
#   function_type: drew
gpu_mem: false
gt:
  attn_dropout: 0.0
  batch_norm: true
  bigbird:
    add_cross_attention: false
    attention_type: block_sparse
    block_size: 3
    chunk_size_feed_forward: 0
    hidden_act: relu
    is_decoder: false
    layer_norm_eps: 1.0e-06
    max_position_embeddings: 128
    num_random_blocks: 3
    use_bias: false
  dim_hidden: 64
  dropout: 0.0
  full_graph: true
  gamma: 1.0e-05
  layer_norm: false
  layer_type: SANLayer
  layers: 3
  n_heads: 8
  pna_degrees: []
  residual: true
max_graph_diameter: 1000
mem:
  inplace: false
metric_agg: argmax
metric_best: ap
# model:
#   edge_decoding: dot
#   graph_pooling: mean
#   loss_fun: cross_entropy
#   match_upper: true
#   size_average: mean
#   thresh: 0.5
#   type: drew-frond
name_tag: ''
num_threads: 6
num_workers: 0
optim:
  base_lr: 0.001
  batch_accumulation: 1
  clip_grad_norm: false
  lr_decay: 0.1
  max_epoch: 300
  min_lr: 1.0e-05
  momentum: 0.9
  num_warmup_epochs: 50
  optimizer: adamW
  reduce_factor: 0.5
  schedule_patience: 20
  scheduler: reduce_on_plateau
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.0
out_dir: results
posenc_ElstaticSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: range(10)
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_EquivStableLapPE:
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  raw_norm_type: none
posenc_HKdiagSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_SignNet:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 64
  phi_out_dim: 4
  post_layers: 0
  raw_norm_type: none
print: both
nu: 1
round: 5
run_dir: results
run_multiple_splits: []
seed: 0
share:
  dim_in: 1
  dim_out: 1
  num_splits: 1
snowflake:
  account: EPA65780
  database: Vrtex
  password: Test12345
  user: yjxxx
  warehouse: SF_TUTS_WH
spn:
  K: 0
tensorboard_agg: true
tensorboard_each_run: false
train:
  auto_resume: false
  batch_size: 128
  ckpt_clean: true
  ckpt_period: 100
  epoch_resume: -1
  eval_period: 1
  finetune: ''
  freeze_pretrained: false
  iter_per_epoch: 32
  mode: custom
  neighbor_sizes:
  - 20
  - 15
  - 10
  - 5
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
  walk_length: 4
use_edge_labels: false
val:
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
view_emb: false
wandb:
  entity: gtransformers
  name: ''
  project: peptides-func
  use: false


# # added below 
# model:
#   type: drew-frond
#   loss_fun: cross_entropy
#   graph_pooling: mean
#   hidden_dim: 256
#   dropout: 0.2
#   input_dropout: 0.6
#   use_mlp: true
#   use_labels: false
#   batch_norm: true
#   fc_out: true
#   function: DREW
#   nu: 1
#   l2norm: true
#   alpha_ode: 0.85
#   time: 40
#   block: constant_frac
#   method: predictor
#   step_size: 1.0
#   layers_mp: 23

#Added 
model:
  type: drew-frond
  loss_fun: bce_with_logits  # Multilabel graph classification Originally cross_entrophy
  graph_pooling: mean
  edge_decoding: dot
  match_upper: true
  size_average: mean
  thresh: 0.5

  # Drew-Frond custom model hyperparams
  hidden_dim: 256
  dropout: 0.2
  input_dropout: 0.6
  use_mlp: true
  use_labels: false
  batch_norm: true
  fc_out: true
  function: DREW
  nu: 1
  l2norm: true
  alpha_ode: 0.85
  time: 40
  block: constant_frac
  method: predictor
  step_size: 1.0
  layers_mp: 23

  
#   act: relu
#   agg: mean
#   att_final_linear: false
#   att_final_linear_bn: false
#   att_heads: 1
#   batchnorm: true
#   clear_feature: true
#   dim_inner: 42
#   dropout: 0.0
#   head: graph
#   keep_edge: 0.5
#   l2norm: true
#   layer_type: drew_gcnconv
#   layers_post_mp: 1
#   layers_pre_mp: 0
#   msg_direction: single
#   normalize_adj: false
#   residual: false
#   self_msg: concat
#   skip_every: 1
#   stage_type: frond_gnn
#   function_type: drew

# -------------------------------------------------------------------------------------------

## Only those used in drew-frond.py from config file are shown here.
# hidden_dim: 256         # Example value, adjust as needed
# dropout: 0.4
# input_dropout: 0.6
# use_mlp: true
# use_labels: false
# batch_norm: true
# fc_out: true
# function: DREW          # or graphcon, laplacian, etc.
# nu: 1
# l2norm: true
# alpha_ode: 0.85
# time: 40
# block: constant_frac   # or constant_frac, etc.
# method: ceuler
# step_size: 1.0

# # Only those used in drew-frond.py from config file are shown here (Drew-frond block).
# drew-frond:
#   hidden_dim: 256         # Example value, adjust as needed
#   dropout: 0.4
#   input_dropout: 0.6
#   use_mlp: true
#   use_labels: false
#   batch_norm: true
#   fc_out: true
#   function: DREW          # or graphcon, laplacian, etc.
#   nu: 1
#   l2norm: true
#   alpha_ode: 0.85
#   time: 40
#   block: constant_graph   # or constant_frac, etc.
#   method: ceuler
#   step_size: 1.0


# # Adding Drew-Frond config file.
# # VERIFY IF ALL THIS NEED TO BE ADDED
# cuda: 1

# # Dataset args
# dataset: twitch-gamer
# data_norm: gcn
# self_loop_weight: 1.0
# use_labels: false
# geom_gcn_splits: true
# num_splits: 1
# label_rate: 0.5
# planetoid_split: false
# random_splits: false
# edge_homo: 0.0

# # GNN args
# hidden_dim: 64
# fc_out: false
# input_dropout: 0.2
# dropout: 0.4
# batch_norm: false
# optimizer: adam
# lr: 0.01
# decay: 0.0001
# epoch: 100
# alpha: 1.0
# alpha_dim: sc
# no_alpha_sigmoid: false
# beta_dim: sc
# block: constant_graph
# function: DREW
# use_mlp: false
# add_source: false
# cgnn: false
# patience: 100

# # ODE args
# time: 3.0
# augment: false
# method: ceuler
# step_size: 1.0
# max_iters: 100
# adjoint_method: adaptive_heun
# adjoint: false
# adjoint_step_size: 1.0
# tol_scale: 1.0
# tol_scale_adjoint: 1.0
# ode_blocks: 1
# max_nfe: 100000000000
# no_early: false
# earlystopxT: 3.0
# max_test_steps: 100

# # Attention args
# leaky_relu_slope: 0.2
# attention_dropout: 0.0
# heads: 4
# attention_norm_idx: 0
# attention_dim: 64
# mix_features: false
# reweight_attention: false
# attention_type: scaled_dot
# square_plus: false

# # Rewiring args
# not_lcc: false

# # Custom ODE parameters
# alpha_ode: 0.5

# # Runtime
# runtime: 1
# seed: 123




# # [STRUCTURED UNDER DREW-FROND BLOCK] This is the new section for your drew-frond config.
# drew-frond:
#   use_cora_defaults: false
#   cuda: 1

#   # Dataset args
#   dataset: twitch-gamer
#   data_norm: gcn
#   self_loop_weight: 1.0
#   use_labels: false
#   geom_gcn_splits: true
#   num_splits: 1
#   label_rate: 0.5
#   planetoid_split: false
#   random_splits: false
#   edge_homo: 0.0

#   # GNN args
#   hidden_dim: 64
#   fc_out: false
#   input_dropout: 0.2
#   dropout: 0.4
#   batch_norm: false
#   optimizer: adam
#   lr: 0.01
#   decay: 0.0001
#   epoch: 100
#   alpha: 1.0
#   alpha_dim: sc
#   no_alpha_sigmoid: false
#   beta_dim: sc
#   block: constant_graph
#   function: DREW
#   use_mlp: false
#   add_source: false
#   cgnn: false
#   patience: 100

#   # ODE args
#   time: 3.0
#   augment: false
#   method: ceuler
#   step_size: 1.0
#   max_iters: 100
#   adjoint_method: adaptive_heun
#   adjoint: false
#   adjoint_step_size: 1.0
#   tol_scale: 1.0
#   tol_scale_adjoint: 1.0
#   ode_blocks: 1
#   max_nfe: 100000000000
#   no_early: false
#   earlystopxT: 3.0
#   max_test_steps: 100

#   # Attention args
#   leaky_relu_slope: 0.2
#   attention_dropout: 0.0
#   heads: 4
#   attention_norm_idx: 0
#   attention_dim: 64
#   mix_features: false
#   reweight_attention: false
#   attention_type: scaled_dot
#   square_plus: false

#   # Rewiring args
#   not_lcc: false

#   # Custom ODE parameters
#   alpha_ode: 0.5

#   # Runtime
#   runtime: 1
#   seed: 123
